name: Nightly Release

on:
  repository_dispatch:
    types: [run-nightly-release]

  workflow_dispatch: # Keep for manual triggering
    inputs:
      version:
        description: 'The version to release (e.g., v0.1.11). Required for manual patch releases.'
        required: false # Not required for scheduled runs
        type: string
      ref:
        description: 'The branch or ref (full git sha) to release from.'
        required: true
        type: string
        default: 'main'
      create_nightly_release:
        description: 'Auto apply the nightly release tag, input version is ignored.'
        required: false
        type: boolean
        default: false
      force_skip_tests:
        description: 'Select to skip the "Run Tests" step in testing. Prod releases should run tests'
        required: false
        type: boolean
        default: false

run-name: Nightly Release v${{ github.event.client_payload.version }}

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: production-release
      url: ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ steps.version.outputs.RELEASE_TAG }}
    if: github.repository == 'hermannhahn/gemini-cli'
    permissions:
      contents: write
      packages: write
      id-token: write
    outputs:
      RELEASE_TAG: ${{ steps.version.outputs.RELEASE_TAG }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }} # Checkout a specific commit
          fetch-depth: 0 # Required for notes generation

      - name: Set nightly
        id: vars
        run: |
          is_nightly="true"
          echo "is_nightly=${is_nightly}" >> $GITHUB_OUTPUT

      - name: Setup Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@hahnd'

      - name: Install Dependencies
        run: npm ci

      - name: Get the version
        id: version
        run: |
          VERSION_JSON=$(node scripts/get-nightly-version.js)
          echo "RELEASE_TAG=$(echo $VERSION_JSON | jq -r .releaseTag)" >> $GITHUB_OUTPUT
          echo "RELEASE_VERSION=$(echo $VERSION_JSON | jq -r .releaseVersion)" >> $GITHUB_OUTPUT
          echo "NPM_TAG=$(echo $VERSION_JSON | jq -r .npmTag)" >> $GITHUB_OUTPUT

      - name: Run Tests
        if: github.event.inputs.force_skip_tests != 'true'
        run: |
          npm run preflight
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Build and Prepare Packages
        run: |
          npm run build:packages
          npm run prepare:package

      - name: Update @hahnd/gemini-cli-core package.json version
        run: |
          PACKAGE_JSON_PATH="packages/core/package.json"
          echo 'Updating version in $PACKAGE_JSON_PATH to ${{ steps.version.outputs.RELEASE_VERSION }}'
          jq ".version=\"${{ steps.version.outputs.RELEASE_VERSION }}\"" $PACKAGE_JSON_PATH > tmp.$$.json && mv tmp.$$.json $PACKAGE_JSON_PATH

      - name: Publish @hahnd/gemini-cli-core
        if: steps.vars.outputs.is_dry_run == 'false'
        run: npm publish --workspace=@hahnd/gemini-cli-core --tag=${{ steps.version.outputs.NPM_TAG }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Update @hahnd/geminid package.json version
        run: |
          PACKAGE_JSON_PATH="packages/cli/package.json"
          echo 'Updating version in $PACKAGE_JSON_PATH to ${{ steps.version.outputs.RELEASE_VERSION }}'
          jq ".version=\"${{ steps.version.outputs.RELEASE_VERSION }}\"" $PACKAGE_JSON_PATH > tmp.$.json && mv tmp.$.json $PACKAGE_JSON_PATH

      - name: Install @hahnd/geminid dependencies
        if: steps.vars.outputs.is_dry_run == 'false'
        run: npm install --workspace=@hahnd/geminid

      - name: Publish @hahnd/geminid
        if: steps.vars.outputs.is_dry_run == 'false'
        run: npm publish --workspace=@hahnd/geminid --tag=${{ steps.version.outputs.NPM_TAG }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release and Tag
        if: ${{ steps.vars.outputs.is_dry_run == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.version.outputs.RELEASE_TAG }} \
            bundle/geminid.js \
            --target ${{ github.sha }} \
            --title "Nightly Release ${{ steps.version.outputs.RELEASE_TAG }}" \
            --generate-notes
