name: Nightly Release

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  nightly_release:
    runs-on: ubuntu-latest
    if: github.repository == 'hermannhahn/gemini-cli'
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: hermannhahn/main # Checkout the main branch
          fetch-depth: 0 # Required for git commands

      - name: Setup Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@hahnd'

      - name: Pull upstream changes
        run: git pull origin hermannhahn/main

      - name: Install Dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run Tests
        run: npm run preflight
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Get Nightly Version
        id: get_nightly_version
        run: |
          # Use the existing script to get the nightly tag name
          VERSION_JSON=$(node scripts/get-release-version.js)
          NIGHTLY_TAG=$(echo $VERSION_JSON | jq -r .nightlyTag)
          echo "NIGHTLY_TAG=$NIGHTLY_TAG" >> $GITHUB_OUTPUT
          echo "NIGHTLY_VERSION=${NIGHTLY_TAG#v}" >> $GITHUB_OUTPUT # Remove 'v' prefix for npm version

      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Build and Prepare Packages
        run: |
          npm run build:packages
          npm run prepare:package

      - name: Publish @hahnd/gemini-cli-core nightly
        run: npm publish --workspace=@hahnd/gemini-cli-core --tag=nightly --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish @hahnd/geminid nightly
        run: npm publish --workspace=@hahnd/geminid --tag=nightly --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NIGHTLY_TAG: ${{ steps.get_nightly_version.outputs.NIGHTLY_TAG }}
        run: |
          gh release create "$NIGHTLY_TAG" \
            --target hermannhahn/main \
            --title "Nightly Release ${{ steps.get_nightly_version.outputs.NIGHTLY_VERSION }}" \
            --generate-notes
