name: Trigger Release

on:
  push:
    branches: [hermannhahn/release]

jobs:
  wait_for_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Gemini CLI CI to complete
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          workflow_file_name: 'ci.yml'
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          ref: hermannhahn/release
          github_token: ${{ secrets.GITHUB_TOKEN }}
          propagate_failure: true

  wait_for_e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for E2E Tests to complete
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          workflow_file_name: 'e2e.yml'
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          ref: hermannhahn/release
          github_token: ${{ secrets.GITHUB_TOKEN }}
          propagate_failure: true

  dispatch_release:
    runs-on: ubuntu-latest
    needs: [wait_for_ci, wait_for_e2e]
    if: ${{ always() && needs.wait_for_ci.result == 'success' && needs.wait_for_e2e.result == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: Get package version
        id: get_version
        run: echo "PACKAGE_VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Dispatch Release Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: run-release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "version": "${{ steps.get_version.outputs.PACKAGE_VERSION }}"}'
