name: 'Trigger Release'

on:
  push:
    branches: ['hermannhahn/release']
  workflow_dispatch:
    inputs:
      force_skip_tests:
        description: 'Select to skip the "Run Tests" step in testing. Prod releases should run tests'
        required: false
        type: 'boolean'
        default: false

jobs:
  wait_for_ci:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Wait for CI'
        uses: 'convictional/trigger-workflow-and-wait@6acf1632a9a81ff2ee5a5a809d6c0fa519eeed3e' # v1.3.0
        with:
          workflow_file_name: 'ci.yml'
          owner: '${{ github.repository_owner }}'
          repo: '${{ github.event.repository.name }}'
          ref: 'hermannhahn/release'
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          propagate_failure: true
          wait_interval: 15

  dispatch_release:
    runs-on: 'ubuntu-latest'
    needs: ['wait_for_ci']
    if: "${{ always() && needs.wait_for_ci.result == 'success' }}"
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8' # ratchet:actions/checkout@v5
        with:
          ref: '${{ github.sha }}'

      - name: 'Get the version'
        id: 'version'
        run: |
          VERSION_JSON=$(node scripts/get-release-version.js)
          echo "RELEASE_TAG=$(echo "$VERSION_JSON" | jq -r .releaseTag)" >> "$GITHUB_OUTPUT"
          echo "RELEASE_VERSION=$(echo "$VERSION_JSON" | jq -r .releaseVersion)" >> "$GITHUB_OUTPUT"
          echo "NPM_TAG=$(echo "$VERSION_JSON" | jq -r .npmTag)" >> "$GITHUB_OUTPUT"

      - name: 'Dispatch Release Workflow'
        uses: 'peter-evans/repository-dispatch@26b39ed245ab8f31526069329e112ab2fb224588'
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          repository: '${{ github.repository }}'
          event-type: 'run-release'
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "version": "${{ steps.version.outputs.RELEASE_VERSION }}"}'
