name: Trigger Release

on:
  push:
    branches: [hermannhahn/main]

jobs:
  wait_for_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Gemini CLI CI to complete
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          workflow_file_name: 'ci.yml'
          ref: hermannhahn/main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          propagate_failure: true

  wait_for_e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for E2E Tests to complete
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          workflow_file_name: 'e2e.yml'
          ref: hermannhahn/main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          propagate_failure: true

  dispatch_release:
    runs-on: ubuntu-latest
    needs: [wait_for_ci, wait_for_e2e]
    if: ${{ always() && needs.wait_for_ci.result == 'success' && needs.wait_for_e2e.result == 'success' }}
    steps:
      - name: Dispatch Release Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: run-release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
